@startmindmap
!theme spacelab
* Tests
**[#343852] [[https://interop.esante.gouv.fr/ Espace de test]]
*** [[https://esante.gouv.fr/sites/default/files/media_entity/documents/CGU_espace_de_tests_v1.1.pdf CGU]]
*** [[https://industriels.esante.gouv.fr/sites/default/files/media/document/manuel_gazelle_evs%20V0.3_1.pdf Manuel]]
**[#D20050] [[https://github.com/ansforge/FIG_ans-ig-sample/wiki/Valider-une-ressource-contre-un-profil HAPI FHIR]]
**[#EAB9BF] Projectathon
*** [[https://industriels.esante.gouv.fr/produits-et-services/ci-sis-cadre-d-interoperabilite-des-systemes-d-information-de-sante/projectathon-interoperabilite Présentation]]
*** [[https://interop.esante.gouv.fr/gazelle/testing/testsDefinition/testsList.seam?testType=2&testStatus=1 Consulter les Tests]]
**[#383837] Verification de conformité
*** [[https://interop.esante.gouv.fr/gazelle/testing/testsDefinition/testsList.seam?testType=5&testStatus=1 Consulter les Tests]]
*** [[https://industriels.esante.gouv.fr/segur-du-numerique-en-sante/toutes-les-ressources-du-segur Programme Ségur]]
@endmindmap


