# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.modele
canonical: https://interop.esante.gouv.fr/ig/fhir/modele # the last part of canonical and id must be the same
name: ExampleIG # Should be an acronym
title: ANS IG Example
description: Description du projet
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 0.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build # le release label doit être conforme au cycle de vie de la doctrine du ci-sis. Cf. https://interop.esante.gouv.fr/ig/documentation/mod_bonnes_pratiques.html#release-dun-ig-fhir colonne "label de publication"

jurisdiction: urn:iso:std:iso:3166#FR "France (la)"

dependencies:
  ans.fr.mos: 0.1.0-ballot

parameters: #Parameters list - https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
    shownav: 'true'
    path-expansion-params: '../../expansion-params.json' # for using French SNOMED CT Extension
    pin-canonicals: pin-all
    apply-contact: true
    logging:
      - tx #tx: Messages describing the use of the terminology server (for debugging)
      - html #html: Log when validating an html page (troubleshooting only - leave off)
      - generate #generate: Log when producing an individual resource (troubleshooting only - leave off)
      - init #init: Messages describing the start up process (for debugging)
      - progress #progress: Overall progress messages
    i18n-default-lang: fr # Default language
    apply-jurisdiction: true
    i18n-lang:
      - en
    translation-sources:
      - input/translations/en


pages:
    index.md:
        title: Accueil
    specifications.md:
        spe-synthese.md:
            title: Synthèse
        spe-processus-collab-1.md:
            title: Processus collaboratif 1
    tests.md: 
        title: Tests
    annexes.md:
        title: Annexes
        annexe-securite.md:
            title: Sécurité
        translationinfo.md:
            title: Informations sur la traduction
        annexe-downloads.md:
            title: Téléchargements et usages
    change-log.md:
        title: Historique des versions

menu:
    Accueil: index.html
    Specifications:
        Synthèse: spe-synthese.html
        Processus collaboratif 1 : spe-processus-collab-1.html
    Ressources de conformité: artifacts.html
    Tests: tests.html
    Annexes:
        Sécurité: annexe-securite.html
        Informations sur la traduction: translationinfo.html
        Téléchargements et usage: annexe-downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/
    Historique: change-log.html
